version: '3.7'
services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /code/app
    command: uvicorn main:app --host 0.0.0.0 --port 8008 --reload
    volumes:
      - ./app:/usr/src
    ports:
      - "8008:8008"
    environment:
      - PORT=8008
      DEBUG: 1
    entrypoint: /start-reload.sh
